stage:
- build

build:
- git clone https://github.com/yanghoon/console
- ls -al
- maven: mvn --version
- node: node -v
- docker: docker version
- kubectl: kubectl version

agent:
  profile: [maven, docker, kubectl]
  containers:
  - name: node
    image: node:8
    ttyEnabled: true
    command: cat
