stage:
- Checkout
- Build
- Deploy

Checkout:
- node:
  - apk add git
  - git clone -b develop https://github.com/yanghoon/console

Build:
- node:
  - npm install -g yarn
  - cd console && yarn install && yarn build
- maven:
  - mvn clean install -Dmaven.repo.local=/root/.m2/${JOB_NAME}
- docker:
  - cd docker && docker build . -t $image
  - docker images | grep cloudzcp
- docker.push:
    imageName: $image
    credentialsId: dockerhub

Deploy:
- kubectl:
  - cd $yaml && bash template.sh
  - kubectl apply -f $yaml/*.yaml
  - kubectl scale deploy zcp-iam --replicas 1

env:
  image: cloudzcp/zcp-portal-ui:1.1.0-alpha
  yaml: k8s/template

agent:
  profile: [maven, docker, kubectl]
  containers:
  - name: node
    image: node:8-alpine   # https://hub.docker.com/r/library/node/
    ttyEnabled: true
    command: cat
  volumes:
  - pvc:zcp-jenkins-mvn-repo: /root/.m2
