stage:
- checkout
- build

checkout:
- node:
  - apk add git
  - git clone https://github.com/yanghoon/console && ls -al

build:
- node:
  - npm install -g yarn
  - cd console && yarn build

agent:
  profile: [maven, docker, kubectl]
  containers:
  - name: node
    image: node:8-alpine   # https://hub.docker.com/r/library/node/
    ttyEnabled: true
    command: cat
