stage:
- checkout
- build

checkout:
- node:
  - apk add git
  - git clone https://github.com/yanghoon/console

build:
- node:
  - npm install -g yarn
  - cd console && yarn install && yarn build
- maven:
  - mvn install
- docker:
  - cd docker && docker build -t cloudzcp/zcp-portal-ui:1.1.0-alpha

agent:
  profile: [maven, docker, kubectl]
  containers:
  - name: node
    image: node:8-alpine   # https://hub.docker.com/r/library/node/
    ttyEnabled: true
    command: cat
