stage:
- build

build:
- ls -al
- git clone https://github.com/yanghoon/console
- ls -al

agent:
  profile: [maven, docker, kubectl]
  containers:
  - name: node
    image: node:8
    ttyEnabled: true
    command: cat
