stage:
- checkout
- build

checkout:
- node:
  - apk add git
  - git clone https://github.com/yanghoon/console

build:
- node:
  - npm install -g yarn
  - cd console && yarn install && yarn build
- maven:
  - mvn clean install -Dmaven.repo.local=/root/.m2/${JOB_NAME}
- docker:
  - cd docker && docker build . -t $image
  - docker images | grep cloudzcp
- docker.push:
    imageName: $image
    credentialsId: dockerhub

env:
  image: cloudzcp/zcp-portal-ui:1.1.0-alpha

agent:
  profile: [maven, docker, kubectl]
  containers:
  - name: node
    image: node:8-alpine   # https://hub.docker.com/r/library/node/
    ttyEnabled: true
    command: cat
  volumes:
  - pvc:zcp-jenkins-mvn-repo: /root/.m2
