spring:
  profiles: local
  
props:
  appName: zcp-portal-local
  keycloak:
    zcp:
      clientId: account
      clientSecret: 944eb586-e550-4577-8081-93f91a22b248
      accessTokenUri: http://localhost:8080/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: ${HOME_URL:http://localhost:8181}/login
  iam:
    baseUrl: https://zcp-iam.cloudzcp.io:443
  alertmanager:
    baseUrl: http://localhost:8080
  dashboard:
    baseUrl: https://dashboard.cloudzcp.io
  addOnService:
    filePath: C:\cloud\temp\upload\
    fileName: addOnServiceMetaData.json
  cliDownloadUrl: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-curl
  zdb:
    enabled: true