spring:
  profiles: dev
  
props:
  appName: zcp-portal-dev
  keycloak:
    zcp:
      clientId: account
      clientSecret: 71ad1e42-d239-4a7d-99f9-e1e50ad7ca93
      accessTokenUri: https://pou-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
      userAuthorizationUri: https://pou-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
      redirectUri: ${HOME_URL:http://localhost:8181}/login
  iam:
    baseUrl: http://localhost:8282
  alertmanager:
    baseUrl: http://localhost:8080
  dashboard:
    baseUrl: https://pou-dev-dashboard.cloudzcp.io
  addOnService:
    filePath: C:\cloud\temp\upload\
    fileName: addOnServiceMetaData.json
  cliDownloadUrl: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-curl
  zdb:
    enabled: true
  

    