server:
  port: 8181
  tomcat:
    uri-encoding: UTF-8
    protocol_header: x-forwarded-proto
  session:
    timeout: 3600
  error:
    whitelabel:
      enabled: false
      
spring:
  application:
    name: zcp-portal
  output:
    ansi:
      enabled: always
  resources:
    chain:
      enabled: true
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    template-resolver-order: 2
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    encoding:
      charset: UTF-8 # the encoding of HTTP requests/responses
      enabled: true # enable http encoding support
      force: true # force the configured encoding

security:
  ignored: health,prometheus
  basic:
    enabled: false

endpoints:
  prometheus:
    sensitive: false

logging:
  level:
    root: INFO 
    org.apache: INFO   
  config: classpath:config/logback-spring.xml
  file : local
  path : data/logs


zuul:
  routes:
#    iam-swagger:
#      path: /iam-api/**          # http://console/iam-api/swagger-ui.html
#      url: ${props.iam.baseUrl}
    iam-api:
      path: /iam/**
      url: ${props.iam.baseUrl}/iam
  
